# Generated by Django 3.0.8 on 2021-04-26 12:29

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210424_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[recipes.models.validate_zero], verbose_name='Cooking time'),
        ),
    ]
